development:
  adapter:   mysql2
  encoding:  utf8
  reconnect: false
  database:  __APPNAME___development
  pool: 5
  username:  root
  password:
  host:      localhost

test:
  adapter:   mysql2
  encoding:  utf8
  reconnect: false
  database:  __APPNAME___test
  pool:      5
  username:  root
  password:
  host:      localhost

production:
  adapter:   postgresql
  encoding:  utf8
  reconnect: false
  database:  __APPNAME___production
  pool:      5
  username:  yourname
  password:  yourpassword
  host:      yourhost
